Lecture_6/Presentation/Week_6_4.MVC/Models/ErrorViewModel.cs
namespace Week_6_4.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lecture_6/Presentation/Week_6_4.MVC/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Week_6_4.Domain.Entities;
using Week_6_4.Persistence.Contexts;

namespace Week_6_4.MVC.Controllers
{
    public class BrandController : Controller
    {
        private readonly ReDoMusicDbContext _dbContext;

        public BrandController()
        {
            _dbContext = new();
        }

        [HttpGet]
        public IActionResult Index()
        {
            var brands = _dbContext.Brands.ToList();

            return View(brands);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(string brandName, string brandDisplayingText, string brandAddress)
        {
            var brand = new Brand()
            {
                Name = brandName,
                DisplayingText = brandDisplayingText,
                Address = brandAddress,
                Id = Guid.NewGuid(),
                CreatedOn = DateTime.UtcNow,
            };

            _dbContext.Brands.Add(brand);

            _dbContext.SaveChanges();

            return View();
        }

        [Route("[controller]/[action]/{id}")]
        public IActionResult Delete(string id)
        {
            var brand = _dbContext.Brands.Where(x => x.Id == Guid.Parse(id)).FirstOrDefault();

            _dbContext.Brands.Remove(brand);

            _dbContext.SaveChanges();

            return RedirectToAction("index");
        }
    }
}

Lecture_6/Presentation/Week_6_4.MVC/Controllers/InstrumentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Week_6_4.Persistence.Contexts;

namespace Week_6_4.MVC.Controllers
{
    public class InstrumentController : Controller
    {
        private readonly ReDoMusicDbContext _dbContext;

        public InstrumentController()
        {
            _dbContext = new();
        }

        public IActionResult Index() //All Instruments will be shown
        {
            var products = _dbContext.Instruments.ToList();

            return View(products);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var brands = _dbContext.Brands.ToList();

            return View(brands);
        }

        [HttpPost]
        public IActionResult Add(string name, string description, string brandId, string price, string barcode, string pictureUrl)
        {
            var brand = _dbContext.Brands.Where(x => x.Id == Guid.Parse(brandId)).FirstOrDefault();

            var instrument = new Domain.Entities.Instrument()
            {
                Id = Guid.NewGuid(),
                Name = name,
                Description = description,
                Barcode = barcode,
                Brand = brand,
                CreatedOn = DateTime.UtcNow,
                PictureUrl = pictureUrl
            };

            _dbContext.Instruments.Add(instrument);

            _dbContext.SaveChanges();

            return RedirectToAction("add");
        }

        [HttpGet]
        [Route("[controller]/[action]/{id}")]
        public IActionResult Inspect(string id)
        {
            var instrument = _dbContext.Instruments.Where(x => x.Id == Guid.Parse(id)).FirstOrDefault();

            return View(instrument);
        }
    }
}

Lecture_6/Presentation/Week_6_4.MVC/Views/Brand/Add.cshtml
<h2>Add Brand</h2>

<form method="post">
    <div class="mb-3 mt-3">
        <label class="form-label">Brand Name:</label>
        <input type="text" class="form-control" placeholder="Enter Brand Name" name="brandName">
    </div>
    <div class="mb-3 mt-3">
        <label class="form-label">Displaing Text:</label>
        <input type="text" class="form-control" placeholder="Enter Displaing Text" name="brandDisplayingText">
    </div>
    <div class="mb-3 mt-3">
        <label class="form-label">Address:</label>
        <input type="text" class="form-control" placeholder="Enter Address" name="brandAddress">
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form> 

Lecture_6/Presentation/Week_6_4.MVC/Views/Brand/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Lecture_6/Presentation/Week_6_4.MVC/Views/Brand/Index.cshtml
@using Week_6_4.Domain.Entities;
@model List<Brand>

<div class="container mt-3">
    <h2>Brands</h2>
    <table class="table table-dark table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Desc.</th>
                <th>Address</th>
                <th width="20px">Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var brand in Model)
            {
                <tr>
                    <td>@brand.Name</td>
                    <td>@brand.DisplayingText</td>
                    <td>@brand.Address</td>
                    <td><a href="/brand/delete/@brand.Id" class="btn btn-danger">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

Lecture_6/Presentation/Week_6_4.MVC/Views/Instrument/Add.cshtml
@using Week_6_4.Domain.Entities;
@model List<Brand>


<form method="post">
    <div class="mb-3 mt-3">
        <label class="form-label">Name:</label>
        <input type="text" class="form-control" placeholder="Enter Instrument Name" name="name">
    </div>
    <div class="mb-3">
        <label class="form-label">Description:</label>
        <input type="text" class="form-control" placeholder="Enter Instrument Description" name="description">
    </div>
    <div class="mb-3">
        <label class="form-label">Price:</label>
        <input type="text" class="form-control" placeholder="Enter Price" name="price">
    </div>
    <div class="mb-3">
        <label class="form-label">Barcode:</label>
        <input type="text" class="form-control" placeholder="Enter Barcode" name="barcode">
    </div>
    <div class="mb-3">
        <label class="form-label">Image:</label>
        <input type="text" class="form-control" placeholder="Enter Barcode" name="pictureUrl">
    </div>
    <br />
    <select name="brandId">
        @foreach (var brand in Model)
        {
            <option value="@brand.Id">@brand.Name</option>
        }
    </select>
    <br />
    <br />


    <button type="submit" class="btn btn-primary">Submit</button>
</form> 

Lecture_6/Presentation/Week_6_4.MVC/Views/Instrument/Index.cshtml
@using Week_6_4.Domain.Entities
@model List<Instrument>

<head>
    <style>
        .row {
            display: flex;
        }

        .column {
            flex: 1;
            padding: 10px;
        }
    </style>
</head>

<body>
    <div class="row">
        @foreach (var product in Model)
        {
                <div class="card column" style="width:400px;">
                    <img class="card-img-top" src="@product.PictureUrl" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title">@product.Name</h4>
                        <p class="card-text">@product.Description</p>
                        <a href="/instrument/inspect/@product.Id" class="btn btn-primary">Inspect</a>
                    </div>
                </div>
        }
    </div>
</body>

Lecture_6/Presentation/Week_6_4.MVC/Views/Instrument/Inspect.cshtml
@using Week_6_4.Domain.Entities;
@model Instrument

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="@Model.PictureUrl" alt="Product Image" class="img-fluid">
            </div>
            <div class="col-md-6">
                <h2 class="my-3">@Model.Name</h2>
                <p>@Model.Description</p>
                <p>Price: $@Model.Price</p>
                <button class="btn btn-outline-success">Buy Now</button>
            </div>
        </div>
    </div>
</body>

Lecture_6/Presentation/Week_6_4.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Week_6_4.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Week_6_4.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="instrument" asp-action="Index"><img src="https://i.pinimg.com/originals/d1/e6/2b/d1e62b72437ea8b418a0f9e08554acc6.png" width="100px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Index">List Brands</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Add">Add Brand</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instrument" asp-action="Add">Add Instrument</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instrument" asp-action="index">List Instruments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Week_6_4.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>